"""Add approval_revoked_on to Request

Revision ID: 1bdf1761448e
Revises: 246c34d033ca
Create Date: 2025-11-08 18:34:20.303533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bdf1761448e'
down_revision = '246c34d033ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_revoked_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_column('approval_revoked_on')

    # ### end Alembic commands ###
