"""Add ClaimRequest table and claim_allowed_for_id to Request

Revision ID: 246c34d033ca
Revises: 371ea9e826cd
Create Date: 2025-11-08 02:34:28.840580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246c34d033ca'
down_revision = '371ea9e826cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('collector_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['request.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claim_allowed_for_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['claim_allowed_for_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('claim_allowed_for_id')

    op.drop_table('claim_request')
    # ### end Alembic commands ###
