"""Added organization verification fields

Revision ID: 6c50240090ea
Revises: 5465210cdb93
Create Date: 2025-11-12 03:44:19.865014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c50240090ea'
down_revision = '5465210cdb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_organization', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('organization_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('license_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('verified_on', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('show_badge', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('show_badge')
        batch_op.drop_column('verified_on')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('license_file')
        batch_op.drop_column('organization_name')
        batch_op.drop_column('is_organization')

    # ### end Alembic commands ###
