"""Add receiver/collector/disposer to Message

Revision ID: bc800856c13f
Revises: 1bdf1761448e
Create Date: 2025-11-08 18:50:25.977303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc800856c13f'
down_revision = '1bdf1761448e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collector_profile_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disposer_profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'profile', ['collector_profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'profile', ['receiver_profile_id'], ['id'])
        batch_op.create_foreign_key(None, 'profile', ['disposer_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('disposer_profile_id')
        batch_op.drop_column('collector_profile_id')
        batch_op.drop_column('receiver_profile_id')

    # ### end Alembic commands ###
